### ISSUE TITLE
Object has no method `delete`

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#35]
Error when deleting a project

### Implementation
```js
$("#deleteProjectButton").click(function() {
    var projectId = document.getElementById('projectID').innerHTML;
    console.log(projectId);

    var postObj = {
      projectId: projectId
    };

    $.ajax({
      type: 'POST',
      url: '/project/remove',
      data: postObj,
      success: function(data) {
        if (data.success == true) {
          console.log(data);
          // So nothing I do here will work anyway...
        }
      },
      error: function(data) {
        swal("Uh-oh!", "There was an unexpected error.", "error");
        console.log(data);
      }
    });
    window.location.reload();
  });
```
Clean and simple... This works correctly.

### Error Message
```
/Users/steventhanna/Desktop/Programming/sails/skrum/api/controllers/ProjectController.js:173
              Project.delete({
                            ^
TypeError: Object #<bound> has no method 'delete'
    at /Users/steventhanna/Desktop/Programming/sails/skrum/api/controllers/ProjectController.js:173:29
    at wrapper (/Users/steventhanna/Desktop/Programming/sails/skrum/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/Users/steventhanna/Desktop/Programming/sails/skrum/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
```

### Recreate Error
1. Pull latest version
1. Drop database
1. Lift sails
1. Login
1. Create project
1. Delete Project
1. Errors for everyone!

I suspect that this is a server side issue, not a client side... Its all yours @sotch-pr35mac.  Happy bug hunting.

**Comment by sotch-pr35mac** [comment]
Well the error reports the message right there, there is no method delete, we just have to replace that with destroy.

**Comment by steventhanna** [comment]
So far so good... However, #37 was the resultant of above changes.
